export let imoPerformance= [
    {
        year : 'An',
        rInt : 'Rang International',
        rAf : 'Rang Africain',
        rAr : 'Rang Arabe',
        or : 'Or',
        ag : 'Argent',
        br: 'Bronze',
        hm: 'HM',
        total : 'Score total'
    }
    ,{
        year : 2026,
        rInt : 77,
        rAf : 2,
        rAr : 3,
        or : 0,
        ag : 0,
        br: 2,
        hm: 1,
        total : 72
    },
    {
        year : 2025,
        rInt : 77,
        rAf : 4,
        rAr : 5,
        or : 0,
        ag : 0,
        br: 0,
        hm: 2,
        total : 58
    },
    { 
        year : 2024,
        rInt : 73,
        rAf : 3,
        rAr : 3, 
        or : 0,
        ag : 0,
        br: 1,
        hm: 3, 
        total :67
    },
    { 
        year : 2023,
        rInt : 75,
        rAf : 4,
        rAr : 5, 
        or : 0,
        ag : 0,
        br: 1,
        hm: 4, 
        total :72
    },
    { 
        year : 2022,
        rInt : 67,
        rAf : 2,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 6, 
        total :85
    },
    { 
        year : 2021,
        rInt : 56,
        rAf : 1,
        rAr : 2, 
        or : 0,
        ag : 1,
        br: 1,
        hm: 2, 
        total :57
    },
    { 
      year: 2020,
        rInt : 71,
        rAf : 2,
        rAr : 3, 
        or : 0,
        ag : 1,
        br: 0,
        hm: 3, 
        total :52
    },
    { 
    year : 2019,
        rInt : 74,
        rAf : 3,
        rAr : 4, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 4, 
        total :48
    },
    { 
        year : 2018,
        rInt : 70,
        rAf : 2,
        rAr : 3, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 3, 
        total :49
    },
    { 
        year : 2017,
        rInt : 79,
        rAf : 2,
        rAr : 3, 
        or : 0,
        ag : 0,
        br: 1,
        hm: 3, 
        total :59
    },
    { 
        year : 2016,
        rInt : 76,
        rAf : 2,
        rAr : 3, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 4, 
        total :50
    },
    { 
        year : 2015,
        rInt : 75,
        rAf : 3,
        rAr : 4, 
        or : 0,
        ag : 0,
        br: 1,
        hm: 2, 
        total :41
    },
    { 
        year : 2014,
        rInt : 80,
        rAf : 3,
        rAr : 4, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 3, 
        total :37
    },
    { 
        year : 2013,
        rInt : 65,
        rAf : 2,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 1,
        hm: 3, 
        total :49
    },
    { 
        year : 2012,
        rInt : 87,
        rAf : 5,
        rAr : 3, 
        or : 0,
        ag : 1,
        br: 0,
        hm: 0, 
        total :25
    },
    { 
        year : 2011,
        rInt : 77,
        rAf : 3,
        rAr : 3, 
        or : 0,
        ag : 0,
        br: 1,
        hm: 1, 
        total :25
    },
    { 
        year : 2010,
        rInt : 81,
        rAf : 4,
        rAr : 3, 
        or : 0,
        ag : 1,
        br: 0,
        hm: 1, 
        total :46
    },
    { 
        year : 2009,
        rInt : 77,
        rAf : 3,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 1,
        hm: 0, 
        total :27
    },
    { 
        year : 2008,
        rInt : 88,
        rAf : 3,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 1, 
        total :20
    },
    { 
        year : 2005,
        rInt : 81,
        rAf : 3,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 0, 
        total :9
        ,
         
        year : 2004,
        rInt : 75,
        rAf : 3,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 1, 
        total :31
    },
    { 
        year : 2002,
        rInt : 72,
        rAf : 3,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 1, 
        total :22
    },
    { 
        year : 2001,
        rInt : 59,
        rAf : 3,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 1,
        hm: 0, 
        total :36
    },
    { 
        year : 1999,
        rInt : 74,
        rAf : 3,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 0, 
        total :22
    },
    { 
        year : 1992,
        rInt : 33,
        rAf : 1,
        rAr : 1, 
        or : 1,
        ag : 0,
        br: 1,
        hm: 0, 
        total :64
    },
    { 
        year : 1991,
        rInt : 39,
        rAf : 2,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 2,
        hm: 1, 
        total :69
    },
    { 
        year : 1990,
        rInt : 45,
        rAf : 2,
        rAr : 3, 
        or : 0,
        ag : 1,
        br: 1,
        hm: 0, 
        total :55
    },
    { 
        year : 1989,
        rInt : 30,
        rAf : 1,
        rAr : 1, 
        or : 0,
        ag : 1,
        br: 0,
        hm: 2, 
        total :81
    },
    { 
        year : 1988,
        rInt : 25,
        rAf : 1,
        rAr : 1, 
        or : 0,
        ag : 0,
        br: 3,
        hm: 0, 
        total :67
    },
    { 
        year : 1986,
        rInt : 19,
        rAf : 2,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 1,
        hm: 0, 
        total :67
    },
    { 
        year : 1985,
        rInt : 28,
        rAf : 2,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 2,
        hm: 0, 
        total :46
    },
    { 
        year : 1984,
        rInt : 30,
        rAf : 3,
        rAr : 3, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 0, 
        total :29
    },
    { 
        year : 1983,
        rInt : 27,
        rAf : 2,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 0, 
        total :26
    },
    { 
        year : 1982,
        rInt : 29,
        rAf : 2,
        rAr : 2, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 0, 
        total :19
    },
    { 
        year : 1981,
        rInt : 26,
        rAf : 1,
        rAr : 1, 
        or : 0,
        ag : 0,
        br: 0,
        hm: 0, 
        total :32
    },

];